# permissions for end users to view podinforedisapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podinforedisapplication-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app-operator
    app.kubernetes.io/part-of: app-operator
    app.kubernetes.io/managed-by: kustomize
  name: podinforedisapplication-viewer-role
rules:
- apiGroups:
  - app.neeraj.angi
  resources:
  - podinforedisapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.neeraj.angi
  resources:
  - podinforedisapplications/status
  verbs:
  - get
