---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.neeraj.angi
  resources:
  - podinforedisapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.neeraj.angi
  resources:
  - podinforedisapplications/finalizers
  verbs:
  - update
- apiGroups:
  - app.neeraj.angi
  resources:
  - podinforedisapplications/status
  verbs:
  - get
  - patch
  - update
