---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.neeraj.angi
  resources:
  - podinforedisapplication
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.neeraj.angi
  resources:
  - podinforedisapplication/finalizers
  verbs:
  - update
- apiGroups:
  - app.neeraj.angi
  resources:
  - podinforedisapplication/status
  verbs:
  - get
  - patch
  - update
